routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::resource('/penduduk', 'PendudukController');
Route::resource('/petugas', 'PetugasController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/kelahiran', 'KelahiranController');
Route::resource('/domisili', 'DomisiliController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Domisili.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Domisili extends Model
{
    protected $fillable = [
        'id',
        'nik',
        'petugas_id',
        'keterangan',
    ];
    protected $table = 'domisili';

    public function penduduk()
    {
        return $this->belongsToMany('App\Penduduk', 'domisili', 'id', 'nik',);
    }
    public function petugas()
    {
        return $this->belongsToMany('App\Petugas', 'domisili', 'id', 'petugas_id');
    }
    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('d F Y');
    }
}

app/Http/Controllers/DomisiliController.php
<?php

namespace App\Http\Controllers;

// use RealRashid\SweetAlert\Facades\Alert;
use Alert;
use App\Domisili;
use App\Petugas;
use App\Penduduk;
use Illuminate\Http\Request;


class DomisiliController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $domisili = Domisili::all();
        $penduduk = Penduduk::all();
        $petugas = Petugas::all();
        return view('domisili.index', compact('domisili', 'penduduk', 'petugas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $petugas = Petugas::all();
        $penduduk = Penduduk::all();
        return view('domisili.create', compact('petugas', 'penduduk'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $domisili = Domisili::create([
            'nik' => $request->nik,
            'keterangan' => $request->keterangan,
            'petugas_id' => $request->petugas_id,
        ]);
        Alert::success('Success', 'Data Domisili berhasil disimpan');
        return redirect()->route('domisili.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $penduduk = Penduduk::all();
        $petugas = Petugas::all();
        $domisili = Domisili::findorfail($id);
        $domisili = Domisili::Find($id);
        return view('domisili.show', compact('domisili', 'penduduk', 'petugas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $penduduk = Penduduk::all();
        $petugas = Petugas::all();
        $domisili = Domisili::findorfail($id);
        return view('domisili.edit', compact('domisili', 'penduduk', 'petugas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $domisili_data = [
            'nik' => $request->nik,
            'keterangan' => $request->keterangan,
            'petugas_id' => $request->petugas_id,
        ];
        Domisili::whereId($id)->update($domisili_data);
        Alert::success('Success', 'Data Domisili berhasil diedit');
        return redirect()->route('domisili.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $domisili = Domisili::findorfail($id);
        $domisili->delete();
        return redirect()->route('domisili.index')->with('success', 'Data Domisili berhasil dihapus');
    }
}

resources/views/domisili/create.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Tambah Surat Domisili
@endsection
@section('content')
<label class="col-md-6">
  <form action="{{ route('domisili.store') }}" method="post">
    @csrf
    <div class="card-body">
      <a href="{{ route('penduduk.create') }}" class="btn btn-sm btn-primary pull-right">Tambah
        Penduduk</a><br /><br />

      <div class="form-group">
        <div class="form-group">
          <label>NIK</label>
          <select name="nik" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik')==$item->nik ? 'selected' : null }}>{{ $item->nik }} -
              {{ $item->name }}

            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <label>Keterangan</label>
        <textarea name="keterangan" class="form-control" rows="3" required></textarea>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>Tanda Tangan</label>
          <select name="petugas_id" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($petugas as $item)
            <option value="{{ $item->id }}" {{ old('petugas_id')==$item->id ? 'selected' : null }}>{{ $item->nama }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-success">
        <a href="" class="btn btn-danger">Batal</a>
      </div>
    </div>
  </form>
</label>
@endsection

resources/views/domisili/edit.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Tambah Surat Domisili
@endsection
@section('content')
<label class="col-md-6">

  <form action="{{ route('domisili.update', $domisili->id)}}" method="post">
    @csrf
    @method('patch')
    <div class="card-body">
      <div class="form-group">
        <div class="form-group">
          <label>NIK</label>
          <select name="nik" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik', $domisili->nik)==$item->id ? 'selected' : null }}>
              {{ $item->nik }} -
              {{ $item->name }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <label>Keterangan</label>
        <textarea name="keterangan" class="form-control" rows="3"
          required>{{ old('keterangan',$domisili->keterangan )}}</textarea>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>Tanda Tangan</label>
          <select name="petugas_id" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($petugas as $item)
            <option value="{{ $item->id }}"
              {{ old('petugas_id', $domisili->petugas_id)==$item->id ? 'selected' : null }}>{{ $item->nama }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <input type="submit" name="tambah_surat_domisili" class="btn btn-success" value="Simpan">
        <a href="" class="btn btn-danger">Batal</a>
      </div>
    </div>
  </form>
</label>
@endsection

resources/views/domisili/index.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Data Domisili
@endsection
@section('content')

<div class="card">
  <!-- /.card-header -->
  <div class="card-body">
    <br>
    @if (Session::has('success'))
    <div class="alert alert-info alert-dismissible">
      <h4><i class="icon fa fa-info"></i> Sukses!</h4>
      {{ Session('success') }}
    </div>
    @endif
    <a href="{{ route('domisili.create') }}" class="btn btn-success btn-sm">Tambah Domisili</a> <br> <br>
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Tanggal</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $no = 0;?>
        @foreach ($domisili as $result)
        <?php $no++ ;?>
        <tr>
          <td>{{ $no }}</td>
          <td>
            {{$result->nik}}
          </td>
          <td>
            {{$result->created_at }}
          </td>
          <td>
            <form action="{{ route('domisili.destroy', $result->id) }}" method="POST">
              @csrf
              @method('delete')
              <a href="{{ route('domisili.edit', $result->id) }}" class="btn btn-primary">Edit</a>
              <button type="submit" class="btn btn-danger">Hapus</button>
              <a target="blank" href="{{ route('domisili.show',$result->id) }}" class="btn btn-info">Cetak</a>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>

  </div>
  @push('script')
  <script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script>
    $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
  </script>
  @endpush
  @endsection

resources/views/domisili/show.blade.php
<style type="text/css">
  @media print and (width: 21cm) and (height: 33cm) {
    @page {
      margin: 1cm;
    }
  }

  .tabelku {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 2px;
  }
</style>
<br /><br /><br />
<center>
  <font size="5"><u><b>SURAT KETERANGAN DOMISILI</b></u></font><br /> <br> Nomor:
  145/ /IV/DS/{{ substr($domisili->created_at, 10, 14) }}
</center>
<br /><br /><br />
<font align="justify">
  Yang bertandatangan di bawah ini , Kepala Desa Warungbambu Kecamatan Karawang Timur Kabupaten Karawang menerangkan :
</font>
<table width="100%">
  <tr>
    <td width="20%">Nama Lengkap</td>
    <td width="3%">:</td>
    <td width="77%">
      @foreach ($domisili->penduduk as $item)
      {{ $item->name }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>NIK</td>
    <td>:</td>
    <td>
      @foreach ($domisili->penduduk as $item)
      {{ $item->nik }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Tempat/Tanggal Lahir</td>
    <td>:</td>
    <td> @foreach ($domisili->penduduk as $item)
      {{ $item->tempat_lahir }}
      @endforeach / @foreach ($domisili->penduduk as $item)
      {{ date('d F Y', strtotime($item->tgl_lahir)) }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Jenis Kelamin</td>
    <td>:</td>
    <td>
      @foreach ($domisili->penduduk as $item)
      {{ $item->jk }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Status Perkawinan</td>
    <td>:</td>
    <td>
      @foreach ($domisili->penduduk as $item)
      {{ $item->status }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Pekerjaan</td>
    <td>:</td>
    <td>
      @foreach ($domisili->penduduk as $item)
      {{ $item->pekerjaan }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Alamat KTP</td>
    <td>:</td>
    <td>
      @foreach ($domisili->penduduk as $item)
      {{ $item->alamat }}
      @endforeach
    </td>
  </tr>
</table>
<font align="justify">
  Berdasarkan Surat pengantar RT/RW setempat, Bahwa yang bersangkutan benar
  saat ini Berdomisili/Bertempat Tinggal di
  @foreach ($domisili->penduduk as $item)
  {{ $item->alamat }}
  @endforeach
  <br /><br />
  Surat Keterangan ini berlaku: {{ $domisili->created_at }} s/d
  {{ date('d F Y', strtotime('+1 month', strtotime($domisili->created_at))) }}
  <br /><br />
  Demikian Surat Keterangan ini dibuat dengan sebenarnya, untuk dapat dipergunakan sesuai keperluannya serta agar yang
  berkepentingan menjadi maklum.<br /><br /><br />
</font>
<table width="100%">
  <tr>
    <td width="50%"></td>
    <td width="50%">
      <center>Warungbambu, {{ $domisili->created_at }} </center>
    </td>
  </tr>
  <tr>
    <td>
      <center>Yang Bersangkutan</center>
    </td>
    <td>
      <center>Kepala Desa Warungbambu</center>
    </td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>
      <center><b><u>
            @foreach ($domisili->penduduk as $item)
            {{ $item->name }}
            @endforeach
          </u></b></center>
    </td>
    <td>
      <center><b><u>
            @foreach ($domisili->petugas as $item)
            {{ $item->nama }}
            @endforeach
          </u></b></center>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
      <center>NIP. @foreach ($domisili->petugas as $item)
        {{ $item->nip }}
        @endforeach</center>
    </td>
  </tr>
</table>
<script>
  window.print();
</script>