routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::resource('/penduduk', 'PendudukController');
Route::resource('/petugas', 'PetugasController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/kelahiran', 'KelahiranController');
Route::resource('/domisili', 'DomisiliController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Pendidikan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pendidikan extends Model
{
    protected $fillable = [
        'id',
        'pendidikan',
    ];
    protected $table = 'pendidikan';
}

app/Http/Controllers/PendidikanController.php
<?php

namespace App\Http\Controllers;

use Alert;
use App\Pendidikan;
use Illuminate\Http\Request;

class PendidikanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pendidikan = Pendidikan::all();
        return view('pendidikan.index', compact('pendidikan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pendidikan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $pendidikan = Pendidikan::create([
            'pendidikan' => $request->pendidikan,

        ]);
        Alert::success('Success', 'Data Pendidikan berhasil disimpan');
        return redirect()->route('pendidikan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pendidikan = Pendidikan::findorfail($id);
        return view('pendidikan.edit', compact('pendidikan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pendidikan_data = [
            'pendidikan' => $request->pendidikan,
        ];
        Pendidikan::whereId($id)->update($pendidikan_data);
        Alert::success('Success', 'Data Pendidikan berhasil diedit');
        return redirect()->route('pendidikan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pendidikan = Pendidikan::findorfail($id);
        $pendidikan->delete();
        Alert::success('Success', 'Data Pendidikan berhasil dihapus');
        return redirect()->route('pendidikan.index');
    }
}

resources/views/pendidikan/create.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Tambah Pendidikan
@endsection
@section('content')
<label class="col-md-6">
  <form action="{{ route('pendidikan.store') }}" method="post">
    @csrf
    <div class="form-group">
      <label>Pendidikan</label>
      <input type="text" name="pendidikan" class="form-control" required />
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Simpan</button>
      <a href="" class="btn btn-danger">Batal</a>
    </div>
  </form>
</label>
@endsection

resources/views/pendidikan/edit.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Edit Pendidikan
@endsection
@section('content')
<label class="col-md-6">
  <form action="{{ route('pendidikan.update', $pendidikan->id)}}" method="post">
    @csrf
    @method('patch')
    <div class="form-group">
      <label>Pendidikan</label>
      <input type="text" name="pendidikan" class="form-control" value="{{ $pendidikan->pendidikan }}" required />
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Simpan</button>
      <a href="" class="btn btn-danger">Batal</a>
    </div>
  </form>
</label>
@endsection

resources/views/pendidikan/index.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Data Pendidikan
@endsection
@section('content')

<div class="card">
  <!-- /.card-header -->
  <div class="card-body">
    <br>
    @if (Session::has('success'))
    <div class="alert alert-info alert-dismissible">
      <h4><i class="icon fa fa-info"></i> Sukses!</h4>
      {{ Session('success') }}
    </div>
    @endif
    <a href="{{ route('pendidikan.create') }}" class="btn btn-success btn-sm">Tambah Pendidikan</a> <br> <br>
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Pendidikan</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $no = 0;?>
        @foreach ($pendidikan as $result )
        <?php $no++ ;?>
        <tr>
          <td>{{ $no }}</td>
          <td>
            {{ $result->pendidikan }}
          </td>
          <td>
            <form action="{{ route('pendidikan.destroy', $result->id) }}" method="POST">
              @csrf
              @method('delete')
              <a href="{{ route('pendidikan.edit', $result->id) }}" class="btn btn-primary">Edit</a>
              <button type="submit" class="btn btn-danger">Hapus</button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>

  </div>
  @push('script')
  <script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script>
    $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
  </script>
  @endpush
  @endsection