routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::resource('/penduduk', 'PendudukController');
Route::resource('/petugas', 'PetugasController');
Route::resource('/pendidikan', 'PendidikanController');
Route::resource('/kelahiran', 'KelahiranController');
Route::resource('/domisili', 'DomisiliController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Kelahiran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Kelahiran extends Model
{

    protected $fillable = [
        'id',
        'nama',
        'nik_ayah',
        'nik_ibu',
        'petugas_id',
        'tempat_lahir',
        'tgl_lahir',
        'jam',
        'jk',
    ];
    protected $table = 'kelahiran';

    public function penduduk()
    {
        return $this->belongsToMany('App\Penduduk', 'kelahiran', 'id', 'nik_ayah',);
    }
    public function pendudukk()
    {
        return $this->belongsToMany('App\Penduduk', 'kelahiran', 'id', 'nik_ibu',);
    }
    public function petugas()
    {
        return $this->belongsToMany('App\Petugas', 'kelahiran', 'id', 'petugas_id');
    }
    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('d F Y');
    }
}

app/Http/Controllers/KelahiranController.php
<?php

namespace App\Http\Controllers;

use Alert;
use App\Kelahiran;
use App\Petugas;
use App\Penduduk;
use Illuminate\Http\Request;

class KelahiranController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kelahiran = Kelahiran::all();
        return view('kelahiran.index', compact('kelahiran'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $petugas = Petugas::all();
        $penduduk = Penduduk::all();
        return view('kelahiran.create', compact('petugas', 'penduduk'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $kelahiran = kelahiran::create([

            'nama' => $request->nama,
            'nik_ayah' => $request->nik_ayah,
            'nik_ibu' => $request->nik_ibu,
            'petugas_id' => $request->petugas_id,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'jam' => $request->jam,
            'jk' => $request->jk,

        ]);
        Alert::success('Success', 'Data Kelahiran berhasil disimpan');
        return redirect()->route('kelahiran.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $penduduk = Penduduk::all();
        $petugas = Petugas::all();
        $kelahiran = Kelahiran::findorfail($id);
        $kelahiran = Kelahiran::Find($id);
        return view('kelahiran.show', compact('kelahiran', 'penduduk', 'petugas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $penduduk = Penduduk::all();
        $petugas = Petugas::all();
        $kelahiran = kelahiran::findorfail($id);
        return view('kelahiran.edit', compact('kelahiran', 'penduduk', 'petugas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kelahiran_data = [
            'nama' => $request->nama,
            'nik_ayah' => $request->nik_ayah,
            'nik_ibu' => $request->nik_ibu,
            'petugas_id' => $request->petugas_id,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->name,
            'jam' => $request->jam,
            'jk' => $request->jk,
            'tgl' => $request->tgl,
        ];
        Kelahiran::whereId($id)->update($kelahiran_data);
        Alert::success('Success', 'Data Kelahiran berhasil diedit');
        return redirect()->route('kelahiran.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kelahiran = Kelahiran::findorfail($id);
        $kelahiran->delete();
        Alert::success('Success', 'Data Kelahiran berhasil dihapus');
        return redirect()->route('kelahiran.index');
    }
}

resources/views/kelahiran/create.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Tambah Surat Kelahiran
@endsection
@section('content')
<label class="col-md-6">
  <form action="{{ route('kelahiran.store') }}" method="post">
    @csrf
    <div class="card-body">
      <a href="{{ route('penduduk.create') }}" class="btn btn-sm btn-primary pull-right">Tambah
        Penduduk</a><br /><br />

      <div class="form-group">
        <div class="form-group">
          <label>NIK Ayah</label>
          <select name="nik_ayah" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik_ayah')==$item->nik ? 'selected' : null }}>{{ $item->nik }} -
              {{ $item->name }}

            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>NIK Ibu</label>
          <select name="nik_ibu" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik_ibu')==$item->nik ? 'selected' : null }}>{{ $item->nik }} -
              {{ $item->name }}

            </option>
            @endforeach
        </div>
        </select>
      </div>

      <div class="form-group">
        <label>Nama Anak</label>
        <input type="text" name="nama" class="form-control" placeholder="Nama Anak" required />
      </div>
      <div class="form-group">
        <label>Jenis Kelamin</label>
        <select name="jk" class="form-control" required>
          <option value="" selected disabled>- pilih -</option>
          <option value="Laki Laki">Laki Laki</option>
          <option value="Perempuan">Perempuan</option>
        </select>
      </div>
      <div class="form-group">
        <label>Tempat Tanggal Lahir</label>
        <div class="row">
          <div class="col-xs-4">
            <input type="text" name="tempat_lahir" class="form-control" placeholder="Tempat">
          </div>
          <div class="col-xs-5">
            <div class="input-group date">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <input type="date" name="tgl_lahir" class="form-control pull-right">
            </div>
          </div>
        </div>
      </div>
      <div class="bootstrap-timepicker">
        <div class="form-group">
          <label>Pukul</label>
          <div class="input-group">
            <input type="time" name="jam" id="pukul" class="form-control timepicker" required>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>Tanda Tangan</label>
          <select name="petugas_id" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($petugas as $item)
            <option value="{{ $item->id }}" {{ old('petugas_id')==$item->id ? 'selected' : null }}>{{ $item->nama }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-success">
        <a href="" class="btn btn-danger">Batal</a>
      </div>
    </div>
  </form>
</label>
@endsection

resources/views/kelahiran/edit.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Tambah Surat Kelahiran
@endsection
@section('content')
<label class="col-md-6">

  <form action="{{ route('kelahiran.update', $kelahiran->id)}}" method="post">
    @csrf
    @method('patch')
    <div class="card-body">
      <div class="form-group">
        <div class="form-group">
          <label>NIK Ayah</label>
          <select name="nik_ayah" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik_ayah', $kelahiran->nik_ayah)==$item->id ? 'selected' : null }}>
              {{ $item->nik }} -
              {{ $item->name }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>NIK Ibu</label>
          <select name="nik_ibu" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($penduduk as $item)
            <option value="{{ $item->id }}" {{ old('nik_ibu', $kelahiran->nik_ibu ) == $item->id ? 'selected' : null }}>
              {{ $item->nik }} -
              {{ $item->name }}
            </option>
            @endforeach

        </div>
        </select>
      </div>

      <div class="form-group">
        <label>Nama Anak</label>
        <input type="text" name="nama" class="form-control" value="{{ old('nama',$kelahiran->nama )}}"
          placeholder="Nama Anak" required />
      </div>
      <div class="form-group">
        <label>Jenis Kelamin</label>
        <select name="jk" class="form-control" required>
          <option value="" selected disabled>{{ old('jk', $kelahiran->jk)}}</option>
          <option value="Laki Laki">Laki Laki</option>
          <option value="Perempuan">Perempuan</option>
        </select>
      </div>
      <div class="form-group">
        <label>Tempat Tanggal Lahir</label>
        <div class="row">
          <div class="col-xs-4">
            <input type="text" name="tempat_lahir" value="{{ old('tempat_lahir',$kelahiran->tempat_lahir )}}"
              class="form-control" placeholder="Tempat">
          </div>
          <div class="col-xs-5">
            <div class="input-group date">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <input type="date" name="tgl_lahir" value="{{ old('tgl_lahir',$kelahiran->tgl_lahir )}}"
                class="form-control pull-right">
            </div>
          </div>
        </div>
      </div>
      <div class="bootstrap-timepicker">
        <div class="form-group">
          <label>Pukul</label>
          <div class="input-group">
            <input type="time" name="jam" id="pukul" value="{{ old('jam',$kelahiran->jam )}}"
              class="form-control timepicker" required>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label>Tanda Tangan</label>
          <select name="petugas_id" class="form-control" required>
            <option value="" selected disabled>- pilih -</option>
            @foreach ($petugas as $item)
            <option value="{{ $item->id }}"
              {{ old('petugas_id', $kelahiran->petugas_id)==$item->id ? 'selected' : null }}>{{ $item->nama }}
            </option>
            @endforeach
        </div>
        </select>
      </div>
      <div class="form-group">
        <input type="submit" name="tambah_surat_kelahiran" class="btn btn-success" value="Simpan">
        <a href="" class="btn btn-danger">Batal</a>
      </div>
    </div>
  </form>
</label>
@endsection

resources/views/kelahiran/index.blade.php
@extends('layout.home')
@push('style')
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('title')
Data Kelahiran
@endsection
@section('content')

<div class="card">
  <!-- /.card-header -->
  <div class="card-body">
    <br>
    @if (Session::has('success'))
    <div class="alert alert-info alert-dismissible">
      <h4><i class="icon fa fa-info"></i> Sukses!</h4>
      {{ Session('success') }}
    </div>
    @endif
    <a href="{{ route('kelahiran.create') }}" class="btn btn-success btn-sm">Tambah kelahiran</a> <br> <br>
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Tanggal Lahir</th>
          <th>Jenis Kelamin</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $no = 0;?>
        @foreach ($kelahiran as $result )
        <?php $no++ ;?>
        <tr>
          <td>{{ $no }}</td>
          <td>
            {{ $result->nama }}
          </td>
          <td>
            {{ date('d F Y', strtotime($result->tgl_lahir)) }}
          </td>
          <td>
            {{ $result->jk }}
          </td>
          <td>
            <form action="{{ route('kelahiran.destroy', $result->id) }}" method="POST">
              @csrf
              @method('delete')
              <a href="{{ route('kelahiran.edit', $result->id) }}" class="btn btn-primary">Edit</a>
              <button type="submit" class="btn btn-danger">Hapus</button>
              <a target="blank" href="{{ route('kelahiran.show',$result->id) }}" class="btn btn-info">Cetak</a>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>

  </div>
  @push('script')
  <script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script>
    $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
  </script>
  @endpush
  @endsection

resources/views/kelahiran/show.blade.php
<style type="text/css">
  @media print and (width: 21cm) and (height: 33cm) {
    @page {
      margin: 1cm;
    }
  }

  .tabelku {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 2px;
  }
</style>
<style type="text/css" media="print">
  @page {
    size: portrait;
  }
</style>
<table width="100%">
  <tr>
    <td width="15%">Desa/Kelurahan</td>
    <td width="1%">:</td>
    <td width="84%">WARUNGBAMBU</td>
  </tr>
  <tr>
    <td>Kecamatan</td>
    <td>:</td>
    <td>KARAWANG TIMUR</td>
  </tr>
  <tr>
    <td>Kabupaten</td>
    <td>:</td>
    <td>KARAWANG</td>
  </tr>
  <tr>
    <td>Provinsi</td>
    <td>:</td>
    <td>JAWA BARAT</td>
  </tr>
</table>
<br /><br />
<center><b>UNTUK YANG BERSANGKUTAN</b> <br />
  <font size="5"><u><b>SURAT KETERANGAN KELAHIRAN</b></u></font><br />Nomor:
  474.1/{{ $kelahiran->id }}/Desa/ {{ substr($kelahiran->created_at, 10, 14) }}
</center>
<br /><br /><br />
<font align="justify">
  Yang bertandatangan di bawah ini, Kepala Desa Warungbambu Kecamatan
  Karawang Timur Kabupaten Karawang, menerangkan bahwa pada:
</font>
<table width="100%">
  <tr>
    <td width="20%"></td>
    <td width="3%"></td>
    <td width="77%"> </td>
  </tr>
  <tr>
    <td>Tempat, Tanggal Lahir</td>
    <td>:</td>
    <td> {{ $kelahiran->tempat_lahir }} / {{ date('d F Y', strtotime($kelahiran->tgl_lahir)) }}
    </td>
  </tr>
  <tr>
    <td>Pukul</td>
    <td>:</td>
    <td>{{ $kelahiran->jam }}</td>
  </tr>
</table>
<br />
<center>Telah lahir seorang anak Bernama
  :<br /><b>"{{ $kelahiran->nama }}"</b><br /></center>
Dari seorang Ibu :
<table width="100%">
  <tr>
    <td width="20%">Nama Lengkap</td>
    <td width="3%">:</td>
    <td width="77%">
      @foreach ($kelahiran->pendudukk as $item)
      {{ $item->name }}
      @endforeach
    </td>
  </tr>
  <tr>
    <td>Pekerjaan</td>
    <td>:</td>
    <td>@foreach ($kelahiran->pendudukk as $item)
      {{ $item->pekerjaan }}
      @endforeach</td>
  </tr>
  <tr>
    <td>Alamat</td>
    <td>:</td>
    <td>@foreach ($kelahiran->pendudukk as $item)
      {{ $item->alamat }}
      @endforeach</td>
  </tr>
</table> <br>
Dari seorang Ayah <br />
<table width="100%">
  <tr>
    <td width="20%">Nama Lengkap</td>
    <td width="3%">:</td>
    <td width="77%">@foreach ($kelahiran->penduduk as $item)
      {{ $item->name }}
      @endforeach</td>
  </tr>
  <tr>
    <td>Pekerjaan</td>
    <td>:</td>
    <td>@foreach ($kelahiran->penduduk as $item)
      {{ $item->pekerjaan }}
      @endforeach</td>
  </tr>
  <tr>
    <td>Alamat</td>
    <td>:</td>
    <td>@foreach ($kelahiran->penduduk as $item)
      {{ $item->alamat }}
      @endforeach</td>
  </tr>
</table>

<br />
<font align="justify">
  Surat Keterangan ini di gunakan sebagaimana mestinya.<br /><br /><br />
</font>
<table width="100%">
  <tr>
    <td width="50%"></td>
    <td width="50%">
      <center>Warungbambu, {{ $kelahiran->created_at }} </center>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
      <center>Kepala Desa Warungbambu</center>
    </td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td>
      <center><b><u>@foreach ($kelahiran->petugas as $item)
            {{ $item->nama }}
            @endforeach</u></b></center>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
      <center>NIP.@foreach ($kelahiran->petugas as $item)
        {{ $item->nip }}
        @endforeach </center>
    </td>
  </tr>
</table>
<script>
  window.print();
</script>